spring:

  datasource:
    url: jdbc:mysql://localhost:3306/worker_service
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  # Disable OpenFeign CircuitBreaker integration
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false

# ==========================
# Server
# ==========================
server:
  port: ${SERVER_PORT:8082}
# ==========================
# Eureka
# ==========================
eureka:
  client:
    enabled: false
    fetch-registry: false
    register-with-eureka: false

# ==========================
# Resilience4j
# ==========================
resilience4j:
  circuitbreaker:
    enabled: false
  timelimiter:
    enabled: false