spring:
  application:
    name: Worker-Service

  web:
    resources:
      static-locations: file:uploads/
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8082}

# ==========================
# Actuator
# ==========================
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true